packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@prisma/client"
  - "prisma"
  - "esbuild"
  - "@node-rs/argon2"

ignoredBuiltDependencies:
  - "@prisma/engines"

allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
